apiVersion: v1
kind: PersistentVolume
metadata:
  name: book-db
  labels:
    app: book-database
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: book-database
  name: book-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
