apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka
  name: eureka
spec:
  ports:
    - port: 8761
      targetPort: 8761
      name: "http"
      protocol: TCP
  selector:
    app: eureka
  clusterIP: None