apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  serviceName: eureka
  replicas: 2
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: eureka:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: eureka-config
              mountPath: /config

      volumes:
        - name: eureka-config
          configMap:
            name: eureka-config